PREFIX mm: <http://megras.org/sparql/mm#>

# Available temporal accessors:
# START
# END
# CREATED

SELECT *
WHERE {
  BIND(mm:START(<http://localhost:8080/iwMDg-D4fHw_nQ35egd4KVW3TnnxyWoVsC58EhAPuS0FMfdFMGZHvaQ>) as ?t)
}