PREFIX megras: <http://megras.org/sparql#>
PREFIX derived: <http://megras.org/derived/>

SELECT ?nn ?similarity
WHERE {
  BIND (<URI> as ?img)
  ?img derived:clipEmbedding ?vec .
  ?nn derived:clipEmbedding ?o .
  BIND (megras:COSINE_SIM(?vec, ?o) as ?similarity)
  FILTER (?img != ?nn)
}
ORDER BY DESC(?similarity) LIMIT 3